# dissecando uma váriavel
a = input ('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaço?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiuscula?', a.isupper())
print('Está em miniscula?', a.islower())
print('Está capitalizada?', a.istitle())
